### ISSUE TITLE
Doubt Reason Based on Entropy

### ISSUE THREAD

**Issue by koaning** [koaning/doubtlab#11]
If a machine learning model is very "confident" then the proba scores will have low entropy. The most uncertain outcome is a uniform distribution which would contain high entropy. Therefore, it could be sensible to add entropy as a reason for doubt.

**Comment by koaning** [comment]
I wonder ... what's a reasonable threshold here?

**Comment by avvorstenbosch** [comment]
I see two ways to use this:
- Return all predictions with a high uncertainty; E > T1
- Return all predictions with a high certainty, that don't match the dataset label; argmax(P) != Y, E < T2

I have been thinking about your question about the threshold, but I haven't been able to figure out a reasonable threshold value. I've been combing through some litterature related to this, but if such a threshold is used, it is often just a hyperparameter that is tuned, without a theoretical argument.
One thing that might help is to use the Normalized Shannon Entropy, since entropy values for distributions with a different number of classes are difficult to compare.  A method that I could see working would be to determine the threshold relative to the entropy distribution of the dataset. The first thing that comes to mind would be to consider the lowest/highest percentiles, although I think there are more clever tricks available.

**Comment by koaning** [comment]
Normalized entropy, as described [here](https://math.stackexchange.com/questions/395121/how-entropy-scales-with-sample-size) seems like a sound idea. I think I'm fine with keeping the threshold as a hyperparameter if that prevents adding an assumption to the stack. I think it'd be good to gather feedback anyway. 

> Return all predictions with a high certainty, that don't match the dataset label; argmax(P) != Y, E < T2

I'm wondering ... is this something best addressed via [WrongPredictionReason](https://koaning.github.io/doubtlab/api/reasons/#doubtlab.reason.WrongPredictionReason). We may want to add a hyperparameter there for this use-case.

**Comment by Garve** [comment]
Hi!

I created a PR for version 1 of the entropy reason [here](https://github.com/koaning/doubtlab/pull/24). I went for a threshold of 0.5, just because it worked well for the iris dataset. 0.2 would have produced way too many non-zeros.

Best
Robert

**Comment by Garve** [comment]
Another way to tackle the "wtf should the threshold be" problem: Maybe we can specify a quantile instead of an absolute threshold like 0.5. This means that we can specify some quantile alpha and then only just flag a share of alpha samples having the highest normalized Shannon entropies.

**Comment by koaning** [comment]
> I'm wondering ... is this something best addressed via WrongPredictionReason. We may want to add a hyperparameter there for this use-case.

We also the `ShortConfidence` reason and the `LongConfidence` reason.

**Comment by koaning** [comment]
> Maybe we can specify a quantile instead of an absolute threshold like 0.5. 

Part of me likes the idea. But I'm worried that we may introduce a lot of hyperparams and that at the moment it's unclear how much more useful doubt based on entropy will be compared to the margin-based reason.

**Comment by GLevV** [comment]
I think it's possible to use Hoover index instead of entropy: it's easier to compute, it is always in 0-1 range and has clear explanation (0 - equality/uniformity, 1 - inequality).

**Comment by koaning** [comment]
I'm wondering ... can we come up with a situation where entropy based doubt can adress issues that the other reasons cannot?

**Comment by koaning** [comment]
Fixed by #24
