### ISSUE TITLE
DisagreeReason, does it have to be two models?

### ISSUE THREAD

**Issue by koaning** [koaning/doubtlab#19]
Maybe you should be able to add three as well?

**Comment by Garve** [comment]
Either this, or you have to stimulate this because with several two model DisagreeReasons and using an appropriate sorting. So far, I think the manual way would be fine, but if you want to find a better way for sorting in the future, it would be better to have a more complex reason. What do you think?

**Comment by koaning** [comment]
I'd like to keep this issue open so folks may give feedback, but before we change the feature we'd need an obvious example that demonstrates the merit. 

Pragmatically, I think this method mainly works when the ML models used work in fundamentally different ways. I think one model that's domain rule based and the other ML based makes a lot of sense. But I'm starting to doubt what a 3rd candidate model might entail.

**Comment by koaning** [comment]
Decided to close this issue. Anybody is free to re-open if they have a compelling example that demonstrates why it needs to be added.
