### ISSUE TITLE
Label properties (or meta data) that make it less likely that a label is correct

### ISSUE THREAD

**Issue by grofte** [koaning/doubtlab#51]
Real data is usually unbalanced but the long tail labels are also more likely to be wrong (whether predicted or human annotated). I don't know how much weight should be assigned to that though. But I figure it could make a Reason class on its own.

Some labels have a hierarchical or aggregative aspect that is predictive about label accuracy, e.g. in ImageNet there are 120 classes that are dog breeds which may be better or worse data compared to other groups of labels. This is more of a metadata thing.

And then there's straight up metadata, e.g. certain annotators may be very unreliable or if the date of annotation is known there may be a correlation that says most of the bad labeling happened at certain stage in the labeling process. But now we are moving into modeling the likelihood of a prediction being true or not.

Tbh it would be nice to have a meld of prodigy and doubtlab where we do active learning on whether the label was right or not (probably with tree-based method sticking to numbers and categories). And then fixing the labels while doing this.

And it would be nice if Prodigy had a more realistic demo for classification where there's hundreds or thousands of possible labels. Very easy to do something with these toy datasets - and when that's in the demo it usually means you have to fight the framework to do anything with a non-toy dataset.

**Comment by koaning** [comment]
> And it would be nice if Prodigy had a more realistic demo for classification where there's hundreds or thousands of possible labels. 

It might help to start off by mentioning that this is a personal project, one that I started in my copious spare time well before joining Explosion. While I understand the link between Prodigy and this project due to the nature of my employment, it would be best to consider the two projects as distinct. Doubtlab is designed to be more for the "scikit learn people", which might overlap with the Prodigy user base, but that's more by coincidence than by design. You don't have to be a Prodigy user to find these tools useful. 

Now on to the topic of "thousands of possible labels". Are these mutually exclusive labels? If they're not, then you could regard each label as a binary classifier and still concern yourself with a single label at a time. If not, then I'd be wondering if you _really_ need 1000 labels for your business problem. It could be that I'm not aware of an application, but I've sofar always found that it's possible to define the problem differently such that you only need a subset of the labels to fulfill a business need. Could you elaborate on the issue that you have that relates to doubtlab? 

> Tbh it would be nice to have a meld of prodigy and doubtlab

There's very little preventing anyone from making a custom recipe that does this 🙂! In essense doubtlab gives you a few tools to prepare a subset of interest to re-evaluate which you can directly pass into Prodigy. It's a trick that is demonstrated in [this Youtube video](https://www.youtube.com/watch?v=khZ5-AN-n2Y&t=2287s). 

> And then there's straight up metadata, e.g. certain annotators may be very unreliable or if the date of annotation is known there may be a correlation that says most of the bad labeling happened at certain stage in the labeling process. 

The more and more that I have been thinking about this, and the and more that I've been exposing myself to [these datasets](https://koaning.io/til/human-variation/) the more that it's starting to feel to me that it mostly boils down to "check the examples where there is disagreement and go from there". If annotators disagree, you should reflect and improve the annotation process to prevent this (maybe the instructions could be made clear). If you're already a Prodigy user however, then there is already a recipe [that helps with this](https://prodi.gy/docs/recipes#review). 

I could consider adding some helpers for doing this with classification problems. But I wonder if it might be more pragmatic if I do this for Prodigy datasets instead. Since on the doubtlab side I'd have to assume a CSV file which isn't what Prodigy typically prefers. 

> Very easy to do something with these toy datasets - and when that's in the demo it usually means you have to fight the framework to do anything with a non-toy dataset.

If you have suggestions for a Prodigy tutorial with a dataset that clearly describes something that we've not covered then the team will be all ears over at [the support forum](https://support.prodi.gy/). As for Doubtlab, does [the 28-label dataset from GoEmotions](https://koaning.github.io/doubtlab/examples/google-emotions/) not cover a compelling use-case?

**Comment by grofte** [comment]
Yeah, I realize this isn't a proper Github issue but I was just thinking about stuff. Sometimes you just gotta ask and you seem like you care about this stuff.

UNSPSC is an example of a labeling system with over 100k labels (https://www.unspsc.org/). They are mutually exclusive though and most catalogs shouldn't use more than hundreds or thousands. CPV codes are much worse since they are typically used in a multilabel context (https://simap.ted.europa.eu/cpv). As for the GoEmotions I think it's a wonderful example of how a multilabel question never really has a right answer which makes everything a bit trickier. 

The data I work with doesn't have multiple annotators (and when they do the labels are overwritten). The thing about something like Prodigy is that my end goal isn't to create a good model but to annotate data efficiently and correctly. Annotation isn't a task but a function or process in our organisation. You can break it down into individual tasks but there will always come new data that needs quality annotation and human work is part of that. 

Right now I'm asking you about quality control stuff because I know there are issues with our existing data and optimizing a model against faulty data is a fool's errand. If I can make a model that lets human work go twice as fast or that can do 50% automatically (but only the 50% that the model can actually predict well) then that's a win. 

I will definitely try the Prodigy support forum =]

**Comment by grofte** [comment]
PS Love Barbara Plank. She's a great lecturer and does cool research.

**Comment by koaning** [comment]
> If I can make a model that lets human work go twice as fast or that can do 50% automatically (but only the 50% that the model can actually predict well) then that's a win.

You may enjoy the keynote I'll give this year for PyData Amsterdam. Recordings should be available after. 

I'm personally not a big fan of having models generate training data without humans in the loop. Having models around to help suggest the most important bits to annotate ... now _that_ is something I highly recommend. This is something doubtlab can help with. 

> The data I work with doesn't have multiple annotators (and when they do the labels are overwritten).

That's a shame. Annotator disagreement usually helps _so much_.

**Comment by grofte** [comment]
Legacy platform with lots of legacy legacies. It's not even that old.

But I'll keep it in mind. We need to do some changes anyway to make sure we don't mix human and AI annotation in our source data.

> You may enjoy the keynote I'll give this year for PyData Amsterdam. Recordings should be available after.

Oh, that sounds great! I'll look forward to that. 

And shouldn't it really be "AI in the loop"? "Human in the loop" sounds like the human only participates when there's an alarm or something :smile:. If I keep my boss in the loop it's not like he's actually going to do any work. Or "AI in the loop" should at least be a fully working iteration in the development process.
